version: '3.9'

services:
  log-insight:
    build: .
    container_name: log-insight
    expose:
      - "8000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
    restart: always

  nginx:
    image: nginx:latest
    container_name: loginsight-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    depends_on:
      - log-insight
    restart: always