version: "3.9"

services:

  ingest:
    build:
      context: .
      dockerfile: docker/ingest.Dockerfile
    container_name: loginsight-ingest
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: always

  query:
    build:
      context: .
      dockerfile: docker/query.Dockerfile
    container_name: loginsight-query
    ports:
      - "8002:8000"
    env_file:
      - .env
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    container_name: loginsight-worker
    env_file:
      - .env
    restart: always

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: loginsight-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dashboard.html:/usr/share/nginx/html/dashboard.html:ro
    depends_on:
      - ingest
      - query
      - worker
    restart: always