worker_processes 1;

events { worker_connections 1024; }

http {
    upstream ingest {
        server ingest:8000;
    }

    upstream query {
        server query:8000;
    }

    server {
        listen 80;

        location /logs/ {
            proxy_pass http://ingest/logs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ingest {
            proxy_pass http://ingest/;
            proxy_set_header Host $host;
        }

        location /results/ {
            proxy_pass http://query/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /query {
            proxy_pass http://query/;
            proxy_set_header Host $host;
        }

        location /dashboard {
            alias /usr/share/nginx/html;
            index dashboard.html;
        }
    }
}
