events {}

http {
    upstream loginsight_backend {
        server log-insight:8000;
        server log-insight:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://loginsight_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}