name: Build & Push DockerHub

on:
  push:
    branches:
      - cloud-native

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push ingest
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/loginsight-ingest:latest ./ingest
        docker push ${{ secrets.DOCKER_USERNAME }}/loginsight-ingest:latest

    - name: Build and push query
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/loginsight-query:latest ./query
        docker push ${{ secrets.DOCKER_USERNAME }}/loginsight-query:latest

    - name: Build and push worker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/loginsight-worker:latest ./worker
        docker push ${{ secrets.DOCKER_USERNAME }}/loginsight-worker:latest